# Generated by Django 2.2.13 on 2020-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarWarsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifiet_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StarWarsCollection',
                'verbose_name_plural': 'StarWarsCollections',
            },
        ),
    ]
